[versions]
agp = "8.3.1"
cardviewV7 = "28.0.0"
firebaseAuthVersion = "22.3.1"
firebaseBom = "32.8.0"
firebaseFirestoreVersion = "24.11.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
googleServices = "4.4.1"
firebaseAnalytics = "21.6.1"
playServicesAuth = "21.0.0"
preference = "1.2.1"
sqlite = "2.4.0"
window = "1.2.0"

[libraries]
cardview-v7 = { module = "com.android.support:cardview-v7", version.ref = "cardviewV7" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
window = { group = "androidx.window", name = "window", version.ref = "window" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

